on: [push]

jobs:
   analyze_repo_meta:
      runs-on: windows-latest
      env:
         OENV_AESPASSPHRASE: ${{ secrets.OENV_AESPASSPHRASE }}
         OENV_COMMITMESSAGE: ${{ github.event.head_commit.message }}
         OENV_GITHUB: ${{ github }}
         OENV_GITHUB_EVENT: ${{ github.event }}
      name: Analyze repository
      steps:
         #  - name: create env file
         #    run: |
         #       touch .env
         #       echo O6S220125GMAILCOM_GITHUBTOKEN =${{ secrets.O6S220125GMAILCOM_GITHUBTOKEN }} >> .env

         # To use this repository's private action,
         # you must check out the repository
         - name: Checkout
           uses: actions/checkout@v2
           #  - name: Phân tích Folder
           #    #run: echo "The time was ${{ steps.hello.outputs.time }}"
           #    run: .\deployFolder.ps1
           #    shell: powershell
         - name: Run nodejs
           run: node .\dist\index.js
